### ISSUE TITLE
Feature Request: Python 3

### ISSUE THREAD

**Issue by DuaneKaufman** [mjbrown/bgapi#15]
Hello,
Is there any movement underway to port bgapi to Python3?
Sincerely,
Duane Kaufman

**Comment by mjbrown** [comment]
I am not aware of any ongoing effort for porting to Python 3.  I've had requests in the past.  I would be happy to review and merge any pull requests that work towards that goal if they don't break Python 2.7 compatibility.

**Comment by pinkavaj** [comment]
There is now Python 3 pull request, pleas review/test/comment/criticize.

**Comment by mjbrown** [comment]
Thank you for the port @pinkavaj I have pushed a version 0.5 to pypi with the python 3 support you added.
