### ISSUE TITLE
Maximum Number of Devices

### ISSUE THREAD

**Issue by Chuseuiti** [mjbrown/bgapi#17]
What is the maximum number of devices that can connect one dongle, I haven't been able to connect more than 3, is that okay?

**Comment by mjbrown** [comment]
I believe they can handle 8, but the device is RAM limited.  It trades GATT
table space for allowing more connections or other things.  It takes a
firmware update to reconfigure it for more connections.  I think you get a
build error if you ask it to do too many things for the RAM space
available.  See config.xml

https://github.com/mjbrown/bgapi/blob/master/test/config.xml

If you're just using it as a client you can probably get eight.
