### ISSUE TITLE
Compatibility with Python 2.6.1?

### ISSUE THREAD

**Issue by CMorton737** [mjbrown/bgapi#32]
Hello,

I appreciate all your work on this package!

I'll soon be implementing this library on an embedded Linux platform running Python 2.6.1.  I see in requirements.txt you list Python 2.7.  Is this a hard requirement, or just the Python version you developed it with? If so, do you know what the specific compatibility issues are between versions?

Thanks!
Chad Morton

**Comment by mjbrown** [comment]
Python 2.7 was the version I developed it with.  I have never used Python 2.6 so I have no idea what dependencies may give you trouble.  If it works, or if you have some changes that make it backwards compatible let me know, or make a pull request yourself and I'll check it out.

**Comment by CMorton737** [comment]
Will do.  Initial results look promising -- no issues yet after running some of the basic tests. I'll keep you posted as I dig deeper.  Thanks!

**Comment by CMorton737** [comment]
Just posting an update -- 0 compatibility issues with bgapi/api after extensive testing.  I haven't used all the features of bgapi/module and won't need to, but no issues to report their either.   Thanks again.
