### ISSUE TITLE
BLED112 as Router

### ISSUE THREAD

**Issue by CMorton737** [mjbrown/bgapi#35]
Im thinking about the possibility of using the BLED112 as a router (read: range extender).  As it stands,  I am using the BLED112 to pick up GAP scan broadcast messages from several temperature sensors. One problem I have is picking up the broadcasts from all the temperature sensors in the area on a single coordinator.  I would like to be able to use the BLED112 to just pass any broadcasts it receives along to the coordinator.  The way I see it is that I have 3 options.

* Use bgapi to configure the BLED112 as a router.  This assumes that the BLED112 has a native router feature (similar to how a Zigbee Xbee module can be configured as a coordinator OR a router). 
* Write a python script to alternate between a 15 second GAP scan, putting all messages into a queue, and then a 15 second GAP broadcast to rebroadcast all messages from queue
* Use two BLED112 modules, one on a continuous GAP scan cycle and then other on a continuous GAP broadcast cycle, and use python to control the immediate rebroadcasting of anything it receives in the scan

Any advice on the best way to proceed?

 (A little more about the temperature sensors:  Each sensor sends its data encrypted in a single broadcast.  This message is broadcasted once a second for 90 seconds in hopes that the coordinator will pick it up in its continues GAP scan.  The process repeats every 10 minutes.)

**Comment by mjbrown** [comment]
The BLED112 has no such router capability.  The BLE112 is ancient tech at this point, ideal for simple projects but not at all suited for mesh networking or multiple client/server functionalities.

A BLE 4.1 capable device, one able to do both central and peripheral simultaneously, could have a scan active at the same time as it broadcasts advertisements.  Some custom firmware would allow you to rebroadcast almost instantaneously from within a single device, as a stand-alone solution.

That said, I would go with option 3 if I were being bribed somehow to use BLED112s.  However, it would take 2-3 times as long to implement versus with custom firmware, and its performance would never be as good, so it would have to be a substantial bribe.

Also, the recently standardized Bluetooth Mesh accomplishes exactly what you're trying to do.  Your problem has been encountered extensively and has finally been solved, but it will be some time before device vendors provide full support.  Nordic (with their nRF52s) already has support.  Other vendors are forthcoming, but beware that many have said "next quarter" for over a year when delivering on new Bluetooth products and standards (I'm looking at you SiLabs).
