### ISSUE TITLE
Python Package Contains Outdated Version

### ISSUE THREAD

**Issue by ryan-summers** [mjbrown/bgapi#39]
The uploaded python package (bgapi) appears to not include support for notifications in BlueGigaServer (e.g. send_attribute), as well as the basic ble_cmd functions for notification support.

The 0.6 version in setup.py needs to be updated from 0.6 to a more up to date version and then reuploaded to PyPI.

**Comment by mjbrown** [comment]
I uploaded version 0.7 to PyPi.
