### ISSUE TITLE
Connect by device name

### ISSUE THREAD

**Issue by JoeHut** [mjbrown/bgapi#41]
I want to connect to a device by its device name but unfortunately can't find a proper attribute in the ``ScanResponse`` class. I also don't find the name in the ``data`` or the parsed ``adv_payload`` attribute. The only way I got it working is by connecting to each device and try to read the name then which obviously is not a satisfying option. Am I missing something obvious?

**Comment by pckbls** [comment]
Hi there,

I ran into the exact same problem. Turned out that I have to call the [`active_scan()`](https://github.com/mjbrown/bgapi/blob/master/bgapi/module.py#L626) method before scanning for devices.

I hope that helps.

**Comment by JoeHut** [comment]
So ``active_scan()`` followed by ``scan_all()`` and then the names are mapped in the ``adv_payload``? I will try it in a second.

**Comment by JoeHut** [comment]
I got it working with adding ``active_scan()`` thanks @pckbls
