### ISSUE TITLE
BLED112 does not disconnect from device if app is closed

### ISSUE THREAD

**Issue by mrzaheri** [mjbrown/bgapi#48]
Hi
I am using the BLED112 and bgapi python library to communicate with the devices. The problem I have is that if the application closes unexpectedly, the adapter stays connected to the device. IS there any settings I am missing in the configuration?

Thanks for your help

**Comment by mjbrown** [comment]
The BLED112 operates independently of the program which is controlling it via serial port.  It has no way of knowing that your program has terminated.

I typically start my scripts by issuing disconnect commands to all connection handles terminating all ongoing procedures using the "reset_ble_state()" method.  It returns the device to a known state.

If it is super critical that you disconnect upon crashing, I have previously used a try: except: finally: to issue the disconnect command.  That implementation is application specific though.
